import React from 'react';
import ReactDOM from 'react-dom';
import {Component, PropTypes} from 'react';
import Cell from "./Cell";
import BoardStore from "../store/BoardStore";
import {store} from "../store/BoardStore";
import {initBoard, clearBoard, updateBoard} from '../actions/actionCreators';
import {Grid, Row, Col, Clearfix, Navbar, Nav, NavItem, Button} from 'react-bootstrap';
import OptionsMenu from "./OptionsMenu";


class Board extends Component {

  constructor(props) {
    super(props);

    this.state = {
      board:store.getState().board,
      start:null,
      maxLength:15,
      generations:0,
      genSpeed:1000,
    };
  }

  //sets size of board
  resizeBoard(size) {
    store.dispatch(initBoard(size,size));

    let newBoard = store.getState().board;

    this.setState({
      board:newBoard,
      maxLength: size,
    });

  }

  //sets rate of board update
  setBoardSpeed(speed) {
    this.setState({
      genSpeed:speed,
    });
  }

  updateBoard() {

    store.dispatch(updateBoard(store.getState().board, this.state.maxLength));

    let newBoard = store.getState().board;

    this.setState({
      board:newBoard,
      generations: this.state.generations + 1,
    });
  }

 //generate matrix of cells with rows and columns
  _generateBoard(state, numOfRows, numOfColumns) {
    let i;
    let rows =[];

    for (i=0;i < numOfRows;i++) {
      let columns = () => {
        let n;
        let col= [];

        for (n=0;n < numOfColumns;n++) {
          col.push(<Cell key={i + "" + n} status={state[i][n].status} row= {i} column= {n}
            renderBoard={this.reRenderBoard.bind(this)}></Cell>);
        }
          return col;
      };

      rows.push(
        <div className="row" key={i}>
          { columns()}
        </div>
      );

    }
    return rows;
  }

  reRenderBoard() {
    let newBoard = store.getState().board;

    this.setState({
      board:newBoard,
    });
  }

//event generated by pushing start
  startBoard(shouldStart) {
    if (shouldStart) {
      this.state.start = setInterval(this.updateBoard.bind(this),this.state.genSpeed);
    }
    else {
      clearInterval(this.state.start);
    }
  }

  render() {
    return (<div>
      <Grid>
      <Row className="show-grid">
          <Col xs={12} md={12}>
           <Navbar inverse className="top-banner action-button">
             <Navbar.Header className="header">
               <Navbar.Brand className="brand nav-align">
               Game Of Life
               </Navbar.Brand>
             </Navbar.Header>
             <Nav className="nav-align">

              <NavItem onClick={(e) => {e.preventDefault(); this.startBoard(true)}}>Run</NavItem>
              <NavItem onClick={(e) => {e.preventDefault(); this.startBoard(false)}}>Pause</NavItem>
              <NavItem onClick={(e) => {
                  e.preventDefault();
                  let newBoard = store.getState().board;

                  store.dispatch(clearBoard(newBoard));
                  this.setState({
                    board:newBoard,
                  });
                  }
                }>Clear</NavItem>
              <NavItem> Generations: {this.state.generations} </NavItem>
             </Nav>

           </Navbar>
           </Col>
      </Row>
      <Row className="show-grid board-holder">
        <Col xs={8} md={8}> <div className="board">
      {this._generateBoard(store.getState().board,this.state.board.length,this.state.board.length)}
      </div>
      </Col>
      </Row>
      <Row>
        <OptionsMenu resizeBoard={this.resizeBoard.bind(this)} setBoardSpeed={this.setBoardSpeed.bind(this)}> </OptionsMenu>
      </Row>
    </Grid>
   </div> );
  }
}

Board.propTypes = {
   board:PropTypes.arrayOf(
      PropTypes.arrayOf(PropTypes.object)),
   start:PropTypes.func,
   maxLength:PropTypes.number,
   generations:PropTypes.number,
};

export default Board